name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Set cloud server config file
      env:
        IDENTIFY_FILE: ${secret.MENGJUNDEMBP_PRIVATE_KEY}
      run: |
        echo $IDENTIFY_FILE
    - name: Deploy to cloud server
      run:  scp -i `echo ${secrets.MENGJUNDEMBP_PRIVATE_KEY}` -r ./README.md root@39.105.149.19:~/
